name: Metrics
on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * *"

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics.languages.svg
          base: ""
          plugin_languages: yes
          plugin_languages_indepth: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_recent_categories: production, markup
          plugin_languages_ignored: html, css
          plugin_languages_limit: 12
          commits_authoring: Devneb01
          theme: tokyo-night
